const actionsTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  MOVE_TO_WISHLIST: "MOVE_TO_WISHLIST",
  CHANGE_QTY: "CHANGE_QTY",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
};
export default actionsTypes;
